name: Build and Deploy to Sigean.nu

on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14
      - run: yarn install
      
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14
      - run: yarn generate
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name sigeantest --account-key SPs1doOFes4UJnWRy7BlL66TQhPg/Vf+fx0jf1sRoQN2ayDITJbohxz/66eXh1H1aP21VSK3l+dbm717RgRkFA== -d '$web' -s ./
          
      - name: Azure logout
        run: |
              az logout
        if: always()
