name: Build and Deploy to Sigean.nu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Yarn generate
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: generate

      - name: Azure Storage Action
        uses: lauchacarro/Azure-Storage-Action@v1.1
        with:
          connection-string: "DefaultEndpointsProtocol=https;AccountName=sigeannutest;AccountKey=1QDmhw0Atstkx7ug9bTxeKg9mX1kbShTRZYqo26fgKJjLJz9FVhIiE368XkPtSISYBp5AkkWSnbPjaFe56Hrnw==;EndpointSuffix=core.windows.net"
          folder: "dist"
