name: Build and Deploy to Sigean.nu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
    
      - name: Deploy to Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        with:
          # The location of your built site files. (For example, "out".)
          source-path: "dist"
          # A SAS URL for your storage account. (You should store this in a Secret.)
          sas-url: "https://sigeannutest.blob.core.windows.net/$web?sp=raw&st=2021-12-18T19:43:29Z&se=2021-12-19T03:43:29Z&spr=https&sv=2020-08-04&sr=c&sig=%2FNRXk1CDeUcDwqR0Gunq%2BqRzWETuZr%2Fr7%2FZ0e6R2ObA%3D"
