name: Build and Deploy to Sigean.nu

on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14
      - run: yarn install
      
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14
      - run: yarn generate
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: js-app
          path: dist
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: js-app
          
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME}} --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -d '$web' -s ./
          
      - name: Azure logout
        run: |
              az logout
        if: always()
